# SciPy Tutorial

## Scipy Intoduction

### SciPy = Scientific Python

SciPy is a collection of mathematical algorithms and convenience functions built on the Numpy extension of Python. It with high-level commands and classes for manipulating and visualizing data. 

The additional benefit of basing SciPy on Python is that this also makes a powerful programming language available for use in developing sophisticated programs and specialized applications. 

Let's start with the contents of tutorial.

## Contents Covered :

#### 1) Basic -  Polynomial
#### 2) Special Funtion 
#### 3) Integration
#### 4) Linear Algebra 
#### 5) Fourier Transformation
#### 6) Interpolation 
#### 7) Statistics
#### 8) Miscellaneous 

## 1) Basic - Polynomial

In [2]:
from numpy import poly1d
p=poly1d([3,6,8])
print(p)

   2
3 x + 6 x + 8


In [3]:
print(p*p)  #(3x^2 + 4^x + 5)^2

   4      3      2
9 x + 36 x + 84 x + 96 x + 64


In [6]:
print(p)
print(" p(2)= ",p(2))
print("p(2) and p(3)=",p([2,3]))

   2
3 x + 6 x + 8
 p(2)=  32
p(2) and p(3)= [32 53]


In [7]:
print("p(2),p(4),p(6) and p(3)=",p([2,4,6,3]))

p(2),p(4),p(6) and p(3)= [ 32  80 152  53]


In [8]:
#Roots of p
p.r

array([-1.+1.29099445j, -1.-1.29099445j])

In [9]:
q=poly1d([1,2,1])
print(q)

   2
1 x + 2 x + 1


In [10]:
q.r

array([-1., -1.])

In [11]:
q

poly1d([1, 2, 1])

In [12]:
print(p)
p1 = poly1d([1,2,3],variable='y') #equation with variable as y
print()
print(p1)

   2
3 x + 6 x + 8

   2
1 y + 2 y + 3


In [14]:
p2 = poly1d([1,2,3],variable='t') #equation with variable as t for time

In [15]:
print(p2)

   2
1 t + 2 t + 3


In [16]:
#Integration of a Polynomial

print(p.integ(k=6)) #k = indefinite integration constant

   3     2
1 x + 3 x + 8 x + 6


In [17]:
#Integration of a Polynomial

print(p.integ()) #k = indefinite integration constant

   3     2
1 x + 3 x + 8 x


In [18]:
# Differentiation of a Polynomial

print(p.deriv())

 
6 x + 6


## 2) Special Function (import scipy.special)

In [19]:
import scipy.special

In [24]:
import numpy as np
a=np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
#Cube Root
scipy.special.cbrt(a)

array([1.        , 1.25992105, 1.44224957, 1.58740105, 1.70997595,
       1.81712059, 1.91293118, 2.        , 2.08008382, 2.15443469])

In [27]:
# Exponent of 10 (exp10())
x = 5
scipy.special.exp10(x)

100000.0

In [28]:
# Exponent of 2 (exp2())
x = 3
scipy.special.exp2(x)

8.0

In [29]:
# Degree to Radian (radian(d,m,s))
d = 30
m = 10
s = 50
scipy.special.radian(d,m,s)

0.5267500645255109

In [30]:
# Trigonometric Funtions (in degrees)
print("Sine of 30 degrees = ",scipy.special.sindg(30))
print("Cosine of 30 degrees = ",scipy.special.cosdg(30))
print("Tangent of 30 degrees = ",scipy.special.tandg(30))

Sine of 30 degrees =  0.49999999999999994
Cosine of 30 degrees =  0.8660254037844387
Tangent of 30 degrees =  0.5773502691896257


In [31]:
# Permutation
scipy.special.perm(5,2) #5P2 = 20

20.0

In [32]:
# Combination
scipy.special.comb(5,2) #5C2 = 10

10.0

## 3) Integration (import scipy.integrate)

### Numerous Types of Integration are available in scipy

   1. quad - Single integration 
   2. dblquad - Double integration 
   3. tplquad - Triple integration 
   4. nquad  - n-fold multiple integration
   5. and many more...

In [33]:
import scipy.integrate

#### Lambda Function in brief

In [35]:
f= lambda x: x**x
f(3)

27

In [36]:
f(5)

3125

In [37]:
5*5*5*5*5

3125

In [38]:
g = lambda x,y : x*y
g(2,3)

6

In [39]:
h = lambda x,y : x**2 + 2*x*y + y**2 #(x+y)^2
h(1,2)  #(1+2)^2

9

In [40]:
f = lambda x : x**3
i = scipy.integrate.quad(f, 1, 2)
i

(3.7500000000000004, 4.1633363423443377e-14)

In [41]:
from numpy import exp
f= lambda x:exp(-x**3)
i = scipy.integrate.quad(f, 1, 4)
i

(0.08546832942957776, 2.1640276156712023e-12)

In [42]:
# Double Integration (Used for area under curve)

#scipy.integrate.dblquad(func, lower_limit, upper_limit, func2, func3)
area = scipy.integrate.dblquad(lambda x, y: x*y, 0, 0.5, lambda x: 0, lambda y: 1-2*y)
area

(0.010416666666666668, 4.101620128472366e-16)